ANALYZE ${schema}.call_center
ANALYZE ${schema}.catalog_page
ANALYZE ${schema}.catalog_returns
ANALYZE ${schema}.catalog_sales
ANALYZE ${schema}.customer
ANALYZE ${schema}.customer_address
ANALYZE ${schema}.customer_demographics
ANALYZE ${schema}.date_dim
ANALYZE ${schema}.household_demographics
ANALYZE ${schema}.income_band
ANALYZE ${schema}.inventory
ANALYZE ${schema}.item
ANALYZE ${schema}.promotion
ANALYZE ${schema}.reason
ANALYZE ${schema}.ship_mode
ANALYZE ${schema}.store
ANALYZE ${schema}.store_returns
ANALYZE ${schema}.store_sales
ANALYZE ${schema}.time_dim
ANALYZE ${schema}.warehouse
ANALYZE ${schema}.web_page
ANALYZE ${schema}.web_returns
ANALYZE ${schema}.web_sales
ANALYZE ${schema}.web_site